---
title: "Selected results"
date: "`r format(Sys.time(), '%B %d, %Y')`"  # "`r Sys.Date()`"
output:
  html_notebook:
    fig_height: 7
    fig_width: 9
    toc: yes
  html_document:
    fig_height: 7
    fig_width: 9
    toc: yes
    toc_depth: 5
---


```{r setup, include=FALSE}
# force the working directory for the notebook file to be the wd of the project - see:
# https://support.rstudio.com/hc/en-us/community/posts/220826588-Working-directory-in-R-Notebooks
#  also see the following, which does not look as good
# https://stackoverflow.com/questions/44816945/why-setting-working-directory-in-r-notebook-doesnt-change-working-directory-in
# knitr::opts_knit$set(root.dir = normalizePath("path")) # wherre path is desired wd

# knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
# knitr::opts_chunk$set(fig.width = ..., fig.height = ...)

```


```{r notes, include=FALSE}
  # html_notebook:
  #   df_print: paged
  #   fig_height: 7
  #   fig_width: 9
  #   toc: yes
  # html_document:
  #   fig_height: 7
  #   fig_width: 9
  #   toc: yes
  #   toc_depth: 5
```


```{r clear_warnings, include=FALSE, eval=FALSE}
# run this line to clear any old warning messages
assign("last.warning", NULL, envir = baseenv())
```


```{r libs, include=FALSE}
source(file.path(PROJHOME, "subprograms", "libraries.r"))

source(file.path(PROJHOME, "subprograms", "globals.r"))
source(file.path(PROJHOME, "subprograms", "functions.r"))
source(file.path(PROJHOME, "subprograms", "functions_assessment_roll.r"))

```


```{r growth, include=FALSE}
# construct mv growth scenarios
globals
# gr_shock_us <- c(.06, .1, .1, .03, -.02, -.06, -.07, -.03, -.01, .02, .05, .05)

greatrec <- read_csv("./data/greatrec_states.csv")
greatrec %>%
  gather(stabbr, pch, -year, -date) %>%
  filter(stabbr %in% c(globals$css, "US")) %>%
  ggplot(aes(year, pch, colour=stabbr)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0)
# looks like years 2003:2017 (15 years) is about right

greatrec_scenarios <- greatrec %>%
  select(-date) %>%
  rename(cyear=year) %>%
  filter(cyear %in% 2002:2017)

growth_scenarios <- greatrec_scenarios
ns(growth_scenarios)

```


```{r runmodel, include=FALSE}
rcdir <- "D:/Dropbox/Open Projects/LILP/PropertyTaxAndInstitutions/ProjectReport/"
rcfn <- "Boyd LILP PropertyTaxInstitutions(6).xlsx"
rcpath <- paste0(rcdir, rcfn)

rc <- read_excel(rcpath, sheet="run_control", skip = 4)

rcuse <- rc %>%
  filter(include==1)
# rcuse
rcuse$runname

a <- proc.time()
avroll <- rcuse %>%
  rowwise() %>% # each row is a scenario
  do(build_assessment_roll(as.list(.), globals, growth_scenarios)) %>%
  ungroup
b <- proc.time()
b - a

#.. create summary of assessment roll ----
glimpse(avroll)

avroll_sum <- avroll %>% 
  group_by(runname, year) %>%
  mutate(numrec=1) %>%
  summarise_at(vars(numrec,
                    starts_with("mvtrue"),
                    reassess_year, av_cycle_sale_year, av_cycle,
                    av_acquisition_sale_year, av_acquisition_ceiling, av_acquisition),
               ~sum(., na.rm=TRUE)) %>%
  mutate(av_total=av_acquisition + av_cycle) %>%
  ungroup
ht(avroll_sum)

```


# Exploratory graphs

```{r xgraphs, include=TRUE}
avroll_sum %>%
  filter(year %in% 1:20) %>%
  select(year, runname, mvtrue, av_total) %>%
  gather(vname, value, -year, -runname) %>%
  ggplot(aes(year, value, colour=vname)) +
  geom_line() +
  geom_hline(yintercept = 100) +
  scale_x_continuous(breaks=seq(0, 40, 2)) +
  facet_wrap(~runname, ncol=2)

avroll_sum %>%
  filter(year %in% 1:20) %>%
  # filter(str_sub(runname, 3, 3)!="_") %>%
  select(year, runname, av_total) %>%
  ggplot(aes(year, av_total, colour=runname)) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 100) +
  scale_x_continuous(breaks=seq(0, 40, 2), limits = c(0, NA))

```


# Graphs for a given state
```{r stgraphs, include=FALSE}
avroll_sum %>%
  filter(year %in% 1:20) %>%
  select(year, runname, mvtrue, av_total) %>%
  gather(vname, value, -year, -runname) %>%
  ggplot(aes(year, value, colour=vname)) +
  geom_line() +
  geom_hline(yintercept = 100) +
  scale_x_continuous(breaks=seq(0, 40, 2)) +
  facet_wrap(~runname, ncol=2)

```
